### ISSUE TITLE
Confluent support for Java version 10

### ISSUE THREAD

**Issue by projdevcv** [confluentinc/kafka-connect-blog#6]
Hi confluent team,
I'm using confluent open source version 4.1.2 on java 8. As part of requirement, I have moved to java version 10.  I got to know that currently Confluent platform is not interoperable with Java 10 .  
I'm  raising this issue to know what higher versions of Confluent will support Java 10 and how soon can I expect Confluent version interoperable with Java 10.

Thanks.

**Comment by ewencp** [comment]
The non-LTS versions (e.g. 9 and 10) go EOL at the same time the next version comes out, which means no updates, including, most importantly, security updates. Because of this, it's not safe to recommend running on these versions unless you can upgrade aggressively when the next version is released. LTS versions like Java 11 are supported for much longer periods, including security updates, so those would be the versions Confluent would support. However, they are not officially supported until they are listed [in the Supported Versions and Interoperability](https://docs.confluent.io/current/installation/versions-interoperability.html) docs. Java 11 support should be coming soon.

I'm going to close this as it's not really related to this repo (by the way, there are some other avenues for asking question like this: https://www.confluent.io/contact/), but feel free to follow up if you have more questions.
